# Generated by Django 5.2.1 on 2025-05-12 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penggajian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_in_month', models.IntegerField()),
                ('status', models.CharField(choices=[('progress', 'Progress'), ('selesai', 'Selesai'), ('aktif', 'Aktif')], default='progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlipGaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaji_pokok', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_potongan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gaji_bersih', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penggajian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penggaji.penggajian')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IzinKeluarMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_out', models.TimeField()),
                ('time_in', models.TimeField()),
                ('nilai_izin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slip_gaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penggaji.slipgaji')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
