# Generated by Django 5.2.1 on 2025-05-12 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='slip_gaji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izin_list', to='penggaji.slipgaji'),
        ),
        migrations.AlterField(
            model_name='slipgaji',
            name='penggajian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slip_gaji', to='penggaji.penggajian'),
        ),
    ]
