# Generated by Django 5.2.1 on 2025-05-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0002_alter_izinkeluarmasuk_slip_gaji_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penggajian',
            options={'ordering': ['-created_at'], 'verbose_name': 'Penggajian', 'verbose_name_plural': 'Penggajian'},
        ),
        migrations.AddField(
            model_name='penggajian',
            name='month',
            field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default=None, help_text='The month for this payroll period', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penggajian',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='penggajian',
            name='days_in_month',
            field=models.IntegerField(help_text='Number of working days in the month'),
        ),
        migrations.AlterField(
            model_name='penggajian',
            name='status',
            field=models.CharField(choices=[('progress', 'Progress'), ('selesai', 'Selesai'), ('aktif', 'Aktif')], default='progress', help_text='Current status of the payroll processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='penggajian',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AddIndex(
            model_name='penggajian',
            index=models.Index(fields=['month'], name='penggaji_pe_month_1da56a_idx'),
        ),
        migrations.AddIndex(
            model_name='penggajian',
            index=models.Index(fields=['status'], name='penggaji_pe_status_8efe8b_idx'),
        ),
    ]
