# Generated by Django 5.2.1 on 2025-06-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0005_alter_slipgaji_gaji_pokok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slipgaji',
            name='gaji_pokok',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base salary amount', max_digits=12),
        ),
    ]
