# Generated by Django 5.2.1 on 2025-06-09 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0007_alter_slipgaji_gaji_pokok'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slipgaji',
            name='total_potongan',
        ),
        migrations.AddField(
            model_name='izinkeluarmasuk',
            name='time_work',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='izinkeluarmasuk',
            name='upah_harian',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slipgaji',
            name='upah_per_menit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='TableGaji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gaji_pokok', models.IntegerField(default=0, help_text='Base salary amount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
