# Generated by Django 5.2.1 on 2025-06-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0008_remove_slipgaji_total_potongan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slipgaji',
            name='gaji_pokok',
        ),
    ]
