# Generated by Django 5.2.1 on 2025-06-10 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0009_remove_slipgaji_gaji_pokok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='nilai_izin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='time_work',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='upah_harian',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
