# Generated by Django 5.2.1 on 2025-06-10 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0010_alter_izinkeluarmasuk_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='time_in',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='time_out',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='time_work',
            field=models.TimeField(blank=True, default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='upah_harian',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
