# Generated by Django 5.2.1 on 2025-06-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0011_alter_izinkeluarmasuk_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='nilai_izin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
