# Generated by Django 5.2.1 on 2025-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0012_alter_izinkeluarmasuk_nilai_izin'),
    ]

    operations = [
        migrations.AddField(
            model_name='slipgaji',
            name='gaji_pokok',
            field=models.IntegerField(default=0, help_text='Base salary amount'),
        ),
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='nilai_izin',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='izinkeluarmasuk',
            name='upah_harian',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='slipgaji',
            name='gaji_bersih',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slipgaji',
            name='upah_per_menit',
            field=models.IntegerField(default=0),
        ),
    ]
