# Generated by Django 5.2.1 on 2025-06-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0013_slipgaji_gaji_pokok_alter_izinkeluarmasuk_nilai_izin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slipgaji',
            name='gaji_pokok',
        ),
    ]
