# Generated by Django 5.2.1 on 2025-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0014_remove_slipgaji_gaji_pokok'),
    ]

    operations = [
        migrations.AddField(
            model_name='izinkeluarmasuk',
            name='potongan',
            field=models.BooleanField(default=False),
        ),
    ]
