# Generated by Django 5.2.1 on 2025-06-27 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0015_izinkeluarmasuk_potongan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='penggajian',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='The month for this payroll period', max_length=20),
        ),
        migrations.CreateModel(
            name='Kasbon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('diterima', 'Diterima'), ('ditolak', 'Ditolak'), ('pending', 'Pending'), ('selesai', 'Selesai')], default='pending', max_length=20)),
                ('nilai_kasbon', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
