# Generated by Django 5.2.1 on 2025-06-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0016_alter_penggajian_month_kasbon'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasbon',
            name='slip_gaji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='penggaji.slipgaji'),
        ),
    ]
