# Generated by Django 5.2.1 on 2025-06-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0017_kasbon_slip_gaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='izinkeluarmasuk',
            name='status_off',
            field=models.BooleanField(default=False),
        ),
    ]
