# Generated by Django 5.2.1 on 2025-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0018_izinkeluarmasuk_status_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='penggajian',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penggajian',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
