# Generated by Django 5.2.1 on 2025-11-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0019_penggajian_date_from_penggajian_date_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablegaji',
            name='gaji_pokok',
        ),
    ]
