# Generated by Django 5.2.1 on 2025-11-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0020_remove_tablegaji_gaji_pokok'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegaji',
            name='gaji_pokok',
            field=models.IntegerField(default=0, help_text='Base salary amount'),
        ),
    ]
