# Generated by Django 5.2.1 on 2025-11-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0021_tablegaji_gaji_pokok'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegaji',
            name='tanggal_bekerja',
            field=models.IntegerField(blank=True, default=4, help_text='Day of the month when the user started working', null=True),
        ),
    ]
