# Generated by Django 5.2.1 on 2025-11-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0022_tablegaji_tanggal_bekerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='penggajian',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the payroll period', null=True),
        ),
    ]
