# Generated by Django 5.2.1 on 2025-11-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0023_penggajian_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablegaji',
            name='tanggal_bekerja',
        ),
    ]
