# Generated by Django 5.2.1 on 2025-11-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0024_remove_tablegaji_tanggal_bekerja'),
    ]

    operations = [
        migrations.AddField(
            model_name='izinkeluarmasuk',
            name='potongan_izin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='izinkeluarmasuk',
            name='potongan_tkm_tmb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='izinkeluarmasuk',
            name='upah_kotor',
            field=models.IntegerField(default=0),
        ),
    ]
