# Generated by Django 5.2.1 on 2026-01-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggaji', '0025_izinkeluarmasuk_potongan_izin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='izinkeluarmasuk',
            name='jam_selesai',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
