# Generated by Django 5.2.1 on 2025-06-30 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama template perhitungan gaji', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Deskripsi tentang template ini')),
                ('is_active', models.BooleanField(default=True, help_text='Status aktif template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penggajiV2.payrolltemplate')),
            ],
            options={
                'unique_together': {('template', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PayrollCalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField()),
                ('input_values', models.JSONField(help_text='Nilai input dalam format JSON')),
                ('calculation_results', models.JSONField(help_text='Hasil perhitungan dalam format JSON')),
                ('final_result', models.DecimalField(decimal_places=2, help_text='Hasil akhir perhitungan gaji', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penggajiV2.payrollassignment')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollCalculationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(help_text='ID unik untuk langkah ini', max_length=50)),
                ('name', models.CharField(help_text='Nama langkah perhitungan', max_length=100)),
                ('operator', models.CharField(choices=[('add', 'Tambah'), ('subtract', 'Kurang'), ('multiply', 'Kali'), ('divide', 'Bagi'), ('percentage', 'Persentase'), ('if_condition', 'Kondisi If'), ('greater_than', 'Lebih Besar Dari'), ('less_than', 'Lebih Kecil Dari'), ('equal', 'Sama Dengan'), ('not_equal', 'Tidak Sama Dengan')], help_text='Operator yang digunakan', max_length=20)),
                ('input1_type', models.CharField(choices=[('variable', 'Variabel'), ('value', 'Nilai'), ('step', 'Hasil Langkah')], help_text='Tipe input pertama', max_length=20)),
                ('input1_value', models.CharField(help_text='Nilai atau referensi input pertama', max_length=255)),
                ('input2_type', models.CharField(blank=True, choices=[('variable', 'Variabel'), ('value', 'Nilai'), ('step', 'Hasil Langkah')], help_text='Tipe input kedua', max_length=20)),
                ('input2_value', models.CharField(blank=True, help_text='Nilai atau referensi input kedua', max_length=255)),
                ('result_variable', models.CharField(help_text='Nama variabel untuk menyimpan hasil', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan eksekusi')),
                ('condition_true_step', models.CharField(blank=True, help_text='ID langkah jika kondisi benar (untuk operator kondisional)', max_length=50)),
                ('condition_false_step', models.CharField(blank=True, help_text='ID langkah jika kondisi salah (untuk operator kondisional)', max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_steps', to='penggajiV2.payrolltemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PayrollVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama variabel (tanpa spasi)', max_length=50)),
                ('display_name', models.CharField(help_text='Nama yang ditampilkan', max_length=100)),
                ('input_type', models.CharField(choices=[('number', 'Angka'), ('text', 'Teks'), ('date', 'Tanggal'), ('time', 'Waktu'), ('boolean', 'Ya/Tidak'), ('select', 'Pilihan')], help_text='Tipe data input', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Apakah wajib diisi')),
                ('default_value', models.CharField(blank=True, help_text='Nilai default', max_length=255)),
                ('options', models.TextField(blank=True, help_text='Opsi untuk tipe select dalam format JSON: [{"value": "1", "label": "Opsi 1"}]')),
                ('order', models.PositiveIntegerField(default=0, help_text='Urutan tampilan')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='penggajiV2.payrolltemplate')),
            ],
        ),
    ]
