# Generated by Django 5.2.1 on 2025-07-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penggajiV2', '0002_alter_payrollcalculationresult_calculation_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollcalculationresult',
            name='input_values',
            field=models.JSONField(help_text='Nilai input dalam format JSON'),
        ),
    ]
